### ISSUE TITLE
Implement scope.partials

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-scope#122]
See https://github.com/canjs/can-stache/issues/304. `scope.partials.foo` should work similar to `scope.vars` but all values should be read from `can-stache-key` using `at: true`.

This will be used in place of
```
<can-import from='can-view-import/test/other.stache!' @value:to='*other' />

{{> *other}}
```

**Comment by phillipskevin** [comment]
This is done in 4.0. No need to add it in 3.0.

**Comment by imaustink** [comment]
My memory is really foggy on this, but I thought we decided to implement in 3.x because there was a confusing warning that had no real solution without `scope.partails`. Am I misremembering things?

**Comment by imaustink** [comment]
@phillipskevin ^

**Comment by phillipskevin** [comment]
I also don't remember, which is why I closed it. If we figure it out, we can re-open.
