### ISSUE TITLE
Tests fail in the production build of CanJS

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-view-scope#128]
This test is currently failing in the production build of CanJS: https://github.com/canjs/can-view-scope/blob/be68cdd959112f3a8d5496789f07947147e8da94/test/scope-test.js#L526

The test gets to this line: https://github.com/canjs/can-view-scope/blob/be68cdd959112f3a8d5496789f07947147e8da94/test/scope-test.js#L550

…then fails because `mapValueDependencies` is undefined.

It’s failing because these lines are removed from the production version: https://github.com/canjs/can-view-scope/blob/be68cdd959112f3a8d5496789f07947147e8da94/compute_data.js#L157-L162

What’s the right way to fix this issue?

**Comment by justinbmeyer** [comment]
We should not test mutated deps in prod. Don’t run the tests in prod.

**Comment by chasenlehara** [comment]
Fixed with https://github.com/canjs/can-view-scope/pull/129
