### ISSUE TITLE
Provide better alternatives to scope.root

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-scope#159]
I have been upgrading a medium sized app from CanJS 2.3 to CanJS 4.0. In the process, I'm removing all of the implicit scope walking. This app had a few properties that were being implicitly read from the application viewModel throughout the application without passing the properties through the component tree. This causes warnings like this one:

```
"public/app/environment-manager/reports/executive-dashboard/executive-dashboard.stache:44: "propertyName" is not in the current scope, so it is being read from a parent scope.
This will not happen automatically in an upcoming release. See https://canjs.com/doc/can-stache.scopeAndContext.html#PreventingScopeWalking.
Use "../../../../../../../propertyName" or "scope.find('propertyName')" instead.
```

No one should ever actually use `"../../../../../../../propertyName"` in a template. There should be a better option.

In this application, `propertyName` is in the application viewModel. Naively, I thought this is probably `scope.root.propertyName`, but the scope walking warning would have told me if this were the case. 

The problem here is that `scope.root` is not the "root"... it's not the top-level scope in this application. `scope.root` actually represents the viewModel of the _current_ component.

Here is what the scopes look like in this app:

![image](https://user-images.githubusercontent.com/5851984/39636404-b08e4d96-4f85-11e8-8082-80ea8a675052.png)

I propose we:
* add a `scope.viewModel` that gives what `scope.root` gives now
* add a `scope.top` that gives the application viewModel (the top-most actual scope)
* deprecate `scope.root`

**Comment by justinbmeyer** [comment]
I'm good with that.  Maybe `scope.vm`?  I honestly still would just like `viewModel` to be a reserved word.  It's so insanely common, it's arguably worth it.

**Comment by phillipskevin** [comment]
I'm also thinking maybe `scope.app` instead of `scope.top`.

**Comment by phillipskevin** [comment]
Decided `scope.app` is no good since it will only be that app if `leakScope` is `true` all the way down.
