### ISSUE TITLE
Fix broken scope walking

### ISSUE THREAD

**Issue by BairDev** [canjs/can-view-scope#183]
I think we are stumbling upon a bug in [this line](https://github.com/canjs/can-view-scope/blob/f7ed66466c78a6c3f54dba0a49811772c52d8dc1/can-view-scope.js#L141).

The code in `scope.read` goes like

```
while (parent.isSpecial()) {
    parent = parent._parent;
}
```

Here parent will be undefined at some point and `parent.isSpecial()` with

> Cannot read property 'isSpecial' of undefined (Chrome)

I'd go with `while (parent && parent.isSpecial())` or something similar.

For some context: we are trying to use something like `{{#if(myList.length)}}` or `{{#if(../myList.length)}}` in a stache view. The workround is adding a `./` or a `this.` to the reference like `{{#if(./myList.length)}}`.

I know that we could and should use `{{#each(myList}}...{{else}}...{{/each}}`, but sometimes we either don't want to iterate or have a different reason for checking the length of a list before iterating over it, e.g. in a `<ul>` context.

**Comment by justinbmeyer** [comment]
Thanks. On my list for monday.

**Comment by justinbmeyer** [comment]
Just to make sure I understand, you have something like `../key` where there is no parent context?

I'm not sure what we should do here.  In some ways an error seems right.  

An example might be:

```js
var scope = new Scope({});

scope.read("../key",{ ... })
```


Should we warn or error?  

Thoughts @phillipskevin / @chasenlehara / @matthewp ?

**Comment by justinbmeyer** [comment]
An error or warning might say:

> MyAppView:1: Unable to find key '../key'.  There is no context at `..`.  Did you mean `./key`?

**Comment by matthewp** [comment]
With leakScope a template might be used in cases where there is a parent context and in other cases where there is not, so I think a warning.

**Comment by justinbmeyer** [comment]
Fixed in: https://github.com/canjs/can-view-scope/releases/tag/v4.7.1
