### ISSUE TITLE
./ scope lookup should read current scope

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-view-scope#54]
@dylanrtt commented on [Thu Mar 24 2016](https://github.com/canjs/canjs/issues/2339)

Introduced in 2.3.14. Similar to #2244.

``` js
var map = new can.Map();
var scope = new can.view.Scope(map);
scope.attr("./") == map; // false
```

http://jsbin.com/mafaroxire/1/edit?html,js,console

---

@justinbmeyer commented on [Thu Sep 01 2016](https://github.com/canjs/canjs/issues/2339#issuecomment-244197193)

Technically, I think this is trying to read the `""` property from the `map`.  I know that:

```
var map = new can.Map();
var scope = new can.view.Scope(map);
scope.attr("./") == map; // false
```

should work.

Is there a reason to use `./`?

---

@dylanrtt commented on [Thu Sep 01 2016](https://github.com/canjs/canjs/issues/2339#issuecomment-244258564)

I don't recall exactly where this came from. Perhaps someone reported it in Gitter. Some people may prefer `./` over `.` for clarity or readability.

---

@justinbmeyer commented on [Fri Sep 02 2016](https://github.com/canjs/canjs/issues/2339#issuecomment-244389269)

@dylanrtt what if someone wants to read the empty string property?  It's a very unlikely case, but `{"":123}` is valid.  Perhaps in 3.0, they could get it with `./[""]`.  I'm just debating if this makes sense semantically, if `./` should represent the same thing as `./[""]` or `.`.

**Comment by justinbmeyer** [comment]
I think we should warn about this.

**Comment by phillipskevin** [comment]
This fix is not correctly pulling the current scope.
