### ISSUE TITLE
Revisit how batchNum is set during dispatch

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-scope#59]
[This change](https://github.com/canjs/can-view-scope/commit/75c9ae7ac1badd19c1bda479a267dd51e030ee9b) was made to make [this check](https://github.com/canjs/can-view-scope/blob/can-reflect/test/scope-test.js#L534) work. Prior to this, the `onValue` handler was fired within a new batch.

This is a sort of hacky solution and should be revisited.

From a conversation with @justinbmeyer:
> another alternative is just to say these updates should fire with the last batch number basically
we essentially "leave" the batch num
until the updateQueue is complete
see if that causes any real problems

**Comment by justinbmeyer** [comment]
canjs doesn't use batch numbers anymore
